spring:
  application:
    name: EurikaServer
server:
  port: 4433

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:4433/eureka